---
- name: git clone citrixcc-taskmaster repo
  git: repo="{{ citrixcc_taskmaster.git_repo_url }}"
       dest="{{ common.scripts_home }}/citrixcc-taskmaster"
       version="{{ citrixcc_taskmaster.version }}"

- name: create config.yml
  template: dest="{{ common.scripts_home }}/citrixcc-taskmaster/config.yml"
            src=citrixcc-taskmaster_config.yml-dist
            owner=scripts
            group=scripts
            mode=600

- name: source virtualenvwrapper
  shell: source /usr/bin/virtualenvwrapper.sh
         creates="{{ common.scripts_home }}/.virtualenvs/initialize"

- name: create citrixcc-taskmaster virtualenv
  shell: . /usr/bin/virtualenvwrapper.sh && mkvirtualenv citrixcc-taskmaster
  args:
    creates: "{{ common.scripts_home }}/.virtualenvs/citrixcc-taskmaster"
    executable: /bin/bash

- name: install requirements
  pip: requirements="{{ common.scripts_home }}/citrixcc-taskmaster/requirements.txt"
       virtualenv="{{ common.scripts_home }}/.virtualenvs/citrixcc-taskmaster"
