# deploy vmware-rbscripts
# this task runs as the jenkins user
---
- name: git clone vmware-rbscripts repo
  git: repo="{{ vmware_rbscripts.git_repo_url }}"
       dest="{{ common.scripts_dir }}/vmware-rbscripts"
       version="{{ vmware_rbscripts.version }}"

- name: install bundler gem
  shell: source $HOME/.bashrc && gem install bundler
  args:
    chdir: "{{ common.scripts_dir }}/vmware-rbscripts"
  changed_when: false

- name: install required gems
  shell: source $HOME/.bashrc && bundle install
  args:
    chdir: "{{ common.scripts_dir }}/vmware-rbscripts"
  changed_when: false
