---
- import_tasks: install_packages.yml
- import_tasks: deploy_citrixcc_taskmaster.yml
  become: yes
  become_user: jenkins
- import_tasks: deploy_vmware_rbscripts.yml
  become: yes
  become_user: jenkins
