---
- name: install autoconf and gcc
  yum:
    name: [ 'autoconf', 'gcc' ]
    state: present

- name: checking for corkscrew
  shell: test -f /usr/local/bin/corkscrew
  register: corkscrew_check
  failed_when: false

- debug: msg="/usr/local/bin/corkscrew already exists, skipping install"
  when: corkscrew_check.rc == 0

- debug: msg="/usr/local/bin/corkscrew does not exist, installing it"
  when: corkscrew_check.rc != 0

- name: copy corkscrew tarball
  copy: src=/private/nfs_backstop/corkscrew-2.0.tar.gz
        dest=/tmp
        mode=700
  when: corkscrew_check.rc != 0

- name: build corkscrew
  script: build_corkscrew.sh
          creates=/usr/local/bin/corkscrew

- name: ensure ~/.ssh exists
  file: path="{{ common.scripts_home }}/.ssh"
        owner=scripts group=scripts mode=700
        state=directory

- name: configure ssh for corkscrew
  copy: dest="{{ common.scripts_home }}/.ssh/config"
        content="Host github.com\nProxyCommand corkscrew proxy.oregonstate.edu 3128 %h %p\nPort 443\nHostname ssh.github.com\n"
        owner=scripts
        group=scripts
        mode=600
