---
- name: install pip and virtualenv
  yum:
    name: [ 'python-pip', 'python-virtualenv' ]
    state: present

- name: install virtualenvwrapper
  pip:
    name: virtualenvwrapper
    state: present

- name: insert/update virtualenvwrapper configuation block in .bashrc
  blockinfile:
    dest: "{{ common.jenkins_home }}/.bashrc"
    block: |
      export WORKON_HOME=$HOME/.virtualenvs
      source /usr/bin/virtualenvwrapper.sh
    marker: "# {mark} ANSIBLE MANAGED BLOCK: virtualenvwrapper"
