---
- include_tasks: setup_user.yml
- include_tasks: install_packages.yml
- include_tasks: install_python.yml
  when: "'python' in group_names"
- include_tasks: install_ruby.yml
  become: yes
  become_user: jenkins
  when: "'ruby' in group_names"
- include_tasks: install_perl.yml
  when: "'perl' in group_names"
