---
- name: create scripts unix group
  group: name=scripts
         state=present

- name: create scripts unix user
  user: name=scripts
        group=scripts
        state=present
        comment="script user"
        shell="/bin/bash"
        home="{{ common.scripts_home }}"
        password="{{ lookup('password', 'scripts_user.txt length=15') }}"
