---
- name: create scripts dir
  file: path={{ common.scripts_dir }}
        state=directory
        owner=jenkins
        group=jenkins
        mode=0755

- name: create .bashrc if necessary
  copy: dest="{{ common.jenkins_home }}/.bashrc"
        src=.bashrc
        force=no
        owner=jenkins
        group=jenkins
        mode=0644

- name: create .bash_profile if necessary
  copy: dest="{{ common.jenkins_home }}/.bash_profile"
        content="source .bashrc"
        force=no
        owner=jenkins
        group=jenkins
        mode=0644
